name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Скачиваем весь код
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Собираем Docker-образ без кеша
      - name: Build Docker image
        run: |
          docker build --no-cache \
            -t cr.yandex/${{ secrets.REGISTRY_ID }}/myapp:${{ github.sha }} \
            .

      # 3) Логинимся в Yandex Container Registry
      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      # 4) Пушим образ в реестр
      - name: Push image to Registry
        run: |
          docker push cr.yandex/${{ secrets.REGISTRY_ID }}/myapp:${{ github.sha }}

      # 5) Деплоим контейнер в Serverless Containers
      - name: Deploy to Serverless Container
        uses: yc-actions/yc-sls-container-deploy@v1
        with:
          yc-sa-json-credentials:      ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id:                   ${{ secrets.FOLDER_ID }}
          container-name:              myapp
          revision-service-account-id: ${{ secrets.SERVICE_ACCOUNT_ID }}
          revision-image-url:          cr.yandex/${{ secrets.REGISTRY_ID }}/myapp:${{ github.sha }}
          revision-cores:              0.5
          revision-memory:             512Mb
          revision-env: |
            NODE_ENV=production
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            SESSION_SECRET=${{ secrets.SESSION_SECRET }}
